development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_development
  pool: 5
  username: postgres
  password: "teste123"

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_test
  pool: 5
  username: postgres
  password: "teste123"